version: "3"
services:
  mongo: 
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes: 
      - ./docker/volumes/mongo:/data/db
    ports:
      - "27017:27017"
  api: 
    container_name: api-container
    build: build .
    image: ecommerce-sertao-nerd
    restart: always
    command: npm start
    volumes: 
      - ./dist:/usr/src/ecommerce-sertao-nerd
    ports: 
      - "5050:5050"
    links: 
      - mongo