version: "3"
services:
  mongo: 
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes: 
      - ./docker/volumes/mongo:/data/db
    ports:
      - "27017:27017"
  api: 
    container_name: api-container
    image: node:12
    working_dir: /usr/src
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/dist/
      - ./package.json:/usr/src/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo